angular.module('mentors4me').value('Constants', {
   //  "DOMAIN" : "http://mentors4me-api-env.364ypmurik.eu-central-1.elasticbeanstalk.com",
   "DOMAIN": "https://mentors4me-api.herokuapp.com",
   "SESSIONS": "/api/sessions",
   "USERS": "/users",
   "ME": "/me",
   "PASWORD": "/password",
   "PROPOSALS": "/api/proposals",
   "INVITATION": "api/invitations",
   "REJECT": "reject",
   "ACCEPT": "accept",
   "ORGANIZATIONS": "/organizations",
   "SKILLS": "/skills",
   "CONTEXTS": "/contexts",
   "MENTORS": "/mentors",
   "DASHBOARD": "/dashboard",
   "PROPOSE_MENTOR": "/propose",
   "LOGIN": "/login",
   "API": "/api",
   "HOME": "/home",
   "NOT_AUTHORIZED": "/notAuthorized",
   "FILTER_BY_STATUS": "?status=",
   "ACCEPTED": "accepted",
   "PENDING": "pending",
   "REJECTED": "rejected",
   "EDIT": "/edit",
   "PROFILE": "/profile/",
   "PROFILE_MENTOR": "/profile/mentor/",
   "PROFILE_ORGANIZATION": "/profile/organization/",
   "TOKEN":"token",
   "USER_ID":"userId",
   "USER_ROLE":"userRole",
   "USER_NAME":"userName",
   "EMPTY":"",
   "CHAT_CHANNEL":"ChatChannel",
   "SENDER":"sender",
   "RECEIVER":"receiver",
   "INVITE":"invite",
   "ORGANIZATION":"organization",
   "MENTOR":"mentor",
   "REGISTER":"/register",
});
