angular.module('mentors4me').value('Constants', {
   //  "DOMAIN" : "http://mentors4me-api-env.364ypmurik.eu-central-1.elasticbeanstalk.com",
   "DOMAIN": "https://mentors4me-api.herokuapp.com",
   "SESSIONS": "/api/sessions",
   "USERS": "/api/users",
   "ME": "/me",
   "PASWORD": "/password",
   "PROPOSALS": "/api/proposals",
   "INVITATION": "api/invitations",
   "REJECT": "reject",
   "ACCEPT": "accept",
   "MENTORS": "/api/mentors",
   "ORGANIZATIONS": "/api/organizations",
   "SKILLS": "/api/skills",
   "CONTEXTS": "/api/contexts",
   "MENTORS": "/mentors",
   "DASHBOARD": "/dashboard",
   "PROPOSE_MENTOR": "/propose",
   "LOGIN": "/login",
   "API": "/api",
   "HOME": "/home",
   "NOT_AUTHORIZED": "/notAuthorized",
   "FILTER_BY_STATUS": "?status=",
   "ACCEPTED": "accepted",
   "PENDING": "pending",
   "REJECTED": "rejected",
   "EDIT": "/edit"
});
